-- RapidX Voice OS - Supabase SaaS schema and RLS
-- Run in Supabase SQL Editor before using the production dashboard.

create table if not exists public.call_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default timezone('utc', now()),
    user_id uuid references auth.users(id) on delete set null,
    phone text not null default 'unknown',
    caller_name text default '',
    duration integer not null default 0,
    transcript text default '',
    summary text default '',
    recording_url text default '',
    sentiment text default 'unknown',
    estimated_cost_usd numeric default 0,
    call_date date,
    call_hour integer,
    call_day_of_week text default '',
    was_booked boolean default false,
    interrupt_count integer default 0
);

create table if not exists public.active_calls (
    room_id text primary key,
    user_id uuid references auth.users(id) on delete set null,
    phone text default 'unknown',
    caller_name text default '',
    status text default 'active',
    last_updated timestamptz default now()
);

create table if not exists public.call_transcripts (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    user_id uuid references auth.users(id) on delete set null,
    call_room_id text,
    phone text default 'unknown',
    role text,
    content text
);

-- Compatibility for earlier table versions.
alter table public.call_logs add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.call_logs add column if not exists phone text default 'unknown';
alter table public.call_logs add column if not exists duration integer default 0;
alter table public.call_logs add column if not exists caller_name text default '';
alter table public.call_logs add column if not exists transcript text default '';
alter table public.call_logs add column if not exists summary text default '';
alter table public.call_logs add column if not exists recording_url text default '';
alter table public.call_logs add column if not exists sentiment text default 'unknown';
alter table public.call_logs add column if not exists estimated_cost_usd numeric default 0;
alter table public.call_logs add column if not exists call_date date;
alter table public.call_logs add column if not exists call_hour integer;
alter table public.call_logs add column if not exists call_day_of_week text default '';
alter table public.call_logs add column if not exists was_booked boolean default false;
alter table public.call_logs add column if not exists interrupt_count integer default 0;
alter table public.active_calls add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.call_transcripts add column if not exists user_id uuid references auth.users(id) on delete set null;

do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'call_logs' and column_name = 'phone_number'
    ) then
        update public.call_logs set phone = phone_number where phone = 'unknown' and phone_number is not null;
    end if;

    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'call_logs' and column_name = 'duration_seconds'
    ) then
        update public.call_logs set duration = duration_seconds where duration = 0 and duration_seconds is not null;
    end if;
end $$;

alter table public.call_logs enable row level security;
alter table public.active_calls enable row level security;
alter table public.call_transcripts enable row level security;

drop policy if exists "Enable all actions for service role" on public.call_logs;
drop policy if exists "Enable all actions for service role" on public.active_calls;
drop policy if exists "Enable all actions for service role" on public.call_transcripts;
drop policy if exists "Users can read own call logs" on public.call_logs;
drop policy if exists "Users can insert own call logs" on public.call_logs;
drop policy if exists "Users can read own active calls" on public.active_calls;
drop policy if exists "Users can read own transcripts" on public.call_transcripts;

create policy "Users can read own call logs"
on public.call_logs
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can insert own call logs"
on public.call_logs
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can read own active calls"
on public.active_calls
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "Users can read own transcripts"
on public.call_transcripts
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create index if not exists idx_call_logs_user_created on public.call_logs(user_id, created_at desc);
create index if not exists idx_call_logs_user_phone on public.call_logs(user_id, phone);
create index if not exists idx_active_calls_user on public.active_calls(user_id);
create index if not exists idx_transcripts_user_room on public.call_transcripts(user_id, call_room_id);

insert into storage.buckets (id, name, public)
values ('call-recordings', 'call-recordings', false)
on conflict (id) do update set public = false;

drop policy if exists "Public read recordings" on storage.objects;
drop policy if exists "Service role write recordings" on storage.objects;
drop policy if exists "Authenticated users can read own recordings" on storage.objects;

create policy "Authenticated users can read own recordings"
on storage.objects
for select
to authenticated
using (
    bucket_id = 'call-recordings'
    and (storage.foldername(name))[1] = (select auth.uid())::text
);
