-- Agent foundation: workspace-scoped agents, immutable versions, provider routes,
-- provider usage events, and audit logs.
-- Run after supabase_migration_v2.sql, supabase_migration_saas_workspaces.sql,
-- and supabase_migration_production_hardening.sql.

create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

alter table public.agents add column if not exists description text not null default '';
alter table public.agents add column if not exists status text not null default 'draft';
alter table public.agents add column if not exists visibility text not null default 'private';
alter table public.agents add column if not exists default_language text not null default 'multilingual';
alter table public.agents add column if not exists created_by uuid references auth.users (id) on delete set null;
alter table public.agents add column if not exists active_version_id uuid;
alter table public.agents add column if not exists deleted_at timestamptz;

create table if not exists public.agent_versions (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents (id) on delete cascade,
  version integer not null,
  status text not null default 'draft',
  welcome_message text not null default 'Hello, this is your AI assistant. Can you hear me?',
  system_prompt text not null default '',
  multilingual_prompts jsonb not null default '{}'::jsonb,
  prompt_variables jsonb not null default '[]'::jsonb,
  llm_config jsonb not null default '{}'::jsonb,
  audio_config jsonb not null default '{}'::jsonb,
  engine_config jsonb not null default '{}'::jsonb,
  call_config jsonb not null default '{}'::jsonb,
  tools_config jsonb not null default '[]'::jsonb,
  analytics_config jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users (id) on delete set null,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (agent_id, version)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'agents_active_version_id_fkey'
      and conrelid = 'public.agents'::regclass
  ) then
    alter table public.agents
      add constraint agents_active_version_id_fkey
      foreign key (active_version_id) references public.agent_versions (id)
      on delete set null;
  end if;
end $$;

create table if not exists public.agent_shares (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references public.agents (id) on delete cascade,
  shared_with_workspace_id uuid not null references public.workspaces (id) on delete cascade,
  permission text not null default 'view',
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (agent_id, shared_with_workspace_id)
);

create table if not exists public.provider_routes (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  route_type text not null,
  primary_provider text not null,
  fallback_providers jsonb not null default '[]'::jsonb,
  cost_limit_usd numeric,
  latency_limit_ms integer,
  config jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.provider_usage_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.workspaces (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  agent_id uuid references public.agents (id) on delete set null,
  agent_version_id uuid references public.agent_versions (id) on delete set null,
  call_log_id bigint references public.call_logs (id) on delete set null,
  provider_type text not null default '',
  provider_name text not null default '',
  model text not null default '',
  metric text not null,
  quantity numeric not null default 0,
  estimated_cost_usd numeric not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.workspaces (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  action text not null,
  entity_type text not null default '',
  entity_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.call_logs add column if not exists agent_version_id uuid references public.agent_versions (id) on delete set null;
alter table public.call_logs add column if not exists published_agent_uuid text;

create index if not exists idx_agents_workspace_status on public.agents (workspace_id, status, created_at desc);
create index if not exists idx_agent_versions_agent_version on public.agent_versions (agent_id, version desc);
create index if not exists idx_agent_versions_agent_status on public.agent_versions (agent_id, status);
create index if not exists idx_agent_shares_workspace on public.agent_shares (shared_with_workspace_id);
create index if not exists idx_provider_routes_workspace on public.provider_routes (workspace_id, route_type, status);
create index if not exists idx_provider_usage_workspace_created on public.provider_usage_events (workspace_id, created_at desc);
create index if not exists idx_audit_logs_workspace_created on public.audit_logs (workspace_id, created_at desc);
create index if not exists idx_call_logs_agent_version on public.call_logs (agent_version_id);
create index if not exists idx_call_logs_published_agent_uuid on public.call_logs (published_agent_uuid);

drop trigger if exists set_agents_updated_at on public.agents;
create trigger set_agents_updated_at
before update on public.agents
for each row execute function public.set_updated_at();

drop trigger if exists set_agent_versions_updated_at on public.agent_versions;
create trigger set_agent_versions_updated_at
before update on public.agent_versions
for each row execute function public.set_updated_at();

drop trigger if exists set_provider_routes_updated_at on public.provider_routes;
create trigger set_provider_routes_updated_at
before update on public.provider_routes
for each row execute function public.set_updated_at();

alter table public.agents enable row level security;
alter table public.agent_versions enable row level security;
alter table public.agent_shares enable row level security;
alter table public.provider_routes enable row level security;
alter table public.provider_usage_events enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "agent_foundation_agents_select_member" on public.agents;
create policy "agent_foundation_agents_select_member"
on public.agents for select to authenticated
using (
  status <> 'deleted'
  and exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = agents.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "agent_foundation_agents_write_admin" on public.agents;
create policy "agent_foundation_agents_write_admin"
on public.agents for all to authenticated
using (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = agents.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = agents.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);

drop policy if exists "agent_foundation_versions_select_member" on public.agent_versions;
create policy "agent_foundation_versions_select_member"
on public.agent_versions for select to authenticated
using (
  exists (
    select 1
    from public.agents a
    join public.workspace_members wm on wm.workspace_id = a.workspace_id
    where a.id = agent_versions.agent_id
      and a.status <> 'deleted'
      and wm.user_id = auth.uid()
  )
);

drop policy if exists "agent_foundation_versions_write_admin" on public.agent_versions;
create policy "agent_foundation_versions_write_admin"
on public.agent_versions for all to authenticated
using (
  exists (
    select 1
    from public.agents a
    join public.workspace_members wm on wm.workspace_id = a.workspace_id
    where a.id = agent_versions.agent_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.agents a
    join public.workspace_members wm on wm.workspace_id = a.workspace_id
    where a.id = agent_versions.agent_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);

drop policy if exists "agent_foundation_shares_select_member" on public.agent_shares;
create policy "agent_foundation_shares_select_member"
on public.agent_shares for select to authenticated
using (
  exists (
    select 1
    from public.agents a
    join public.workspace_members owner_wm on owner_wm.workspace_id = a.workspace_id
    where a.id = agent_shares.agent_id and owner_wm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.workspace_members shared_wm
    where shared_wm.workspace_id = agent_shares.shared_with_workspace_id
      and shared_wm.user_id = auth.uid()
  )
);

drop policy if exists "agent_foundation_shares_write_admin" on public.agent_shares;
create policy "agent_foundation_shares_write_admin"
on public.agent_shares for all to authenticated
using (
  exists (
    select 1
    from public.agents a
    join public.workspace_members wm on wm.workspace_id = a.workspace_id
    where a.id = agent_shares.agent_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
)
with check (
  exists (
    select 1
    from public.agents a
    join public.workspace_members wm on wm.workspace_id = a.workspace_id
    where a.id = agent_shares.agent_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);

drop policy if exists "agent_foundation_provider_routes_member" on public.provider_routes;
create policy "agent_foundation_provider_routes_member"
on public.provider_routes for all to authenticated
using (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = provider_routes.workspace_id and wm.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = provider_routes.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);

drop policy if exists "agent_foundation_provider_usage_select_member" on public.provider_usage_events;
create policy "agent_foundation_provider_usage_select_member"
on public.provider_usage_events for select to authenticated
using (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = provider_usage_events.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "agent_foundation_audit_select_admin" on public.audit_logs;
create policy "agent_foundation_audit_select_admin"
on public.audit_logs for select to authenticated
using (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = audit_logs.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);
