-- Production hardening: retries, analytics fields, RLS, agents, usage.
-- Run after supabase_migration_v2.sql and supabase_migration_saas_workspaces.sql.

create extension if not exists "pgcrypto";

alter table public.call_logs add column if not exists status text not null default 'completed';
alter table public.call_logs add column if not exists retry_count integer not null default 0;
alter table public.call_logs add column if not exists max_retries integer not null default 3;
alter table public.call_logs add column if not exists next_retry_at timestamptz;
alter table public.call_logs add column if not exists failure_reason text not null default '';
alter table public.call_logs add column if not exists room_name text not null default '';
alter table public.call_logs add column if not exists agent_id text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'call_logs_status_check'
      and conrelid = 'public.call_logs'::regclass
  ) then
    alter table public.call_logs add constraint call_logs_status_check
      check (status in ('dispatching', 'dispatched', 'answered', 'completed', 'retry_scheduled', 'retrying', 'failed'));
  end if;
end $$;

create index if not exists idx_call_logs_retry_due
  on public.call_logs (next_retry_at)
  where status = 'retry_scheduled';

create index if not exists idx_call_logs_status_created
  on public.call_logs (status, created_at desc);

create table if not exists public.agents (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references public.workspaces (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  name text not null default 'Voice Agent',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid references public.workspaces (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  call_log_id bigint references public.call_logs (id) on delete set null,
  metric text not null,
  quantity numeric not null default 0,
  estimated_cost_usd numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references public.workspaces (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  name text not null,
  status text not null default 'draft',
  total_calls integer not null default 0,
  completed_calls integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.billing_accounts (
  workspace_id uuid primary key references public.workspaces (id) on delete cascade,
  plan text not null default 'Launch',
  status text not null default 'trial',
  stripe_customer_id text,
  stripe_subscription_id text,
  included_minutes integer not null default 250,
  updated_at timestamptz not null default now()
);

create index if not exists idx_agents_workspace on public.agents (workspace_id);
create index if not exists idx_usage_workspace_created on public.usage_events (workspace_id, created_at desc);
create index if not exists idx_campaigns_workspace_created on public.campaigns (workspace_id, created_at desc);

alter table public.call_logs enable row level security;
alter table public.active_calls enable row level security;
alter table public.call_transcripts enable row level security;
alter table public.agents enable row level security;
alter table public.usage_events enable row level security;
alter table public.campaigns enable row level security;
alter table public.billing_accounts enable row level security;

drop policy if exists "prod_call_logs_select_member" on public.call_logs;
create policy "prod_call_logs_select_member"
on public.call_logs for select to authenticated
using (
  (workspace_id is null and user_id = auth.uid())
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = call_logs.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "prod_active_calls_select_member" on public.active_calls;
create policy "prod_active_calls_select_member"
on public.active_calls for select to authenticated
using (
  (workspace_id is null and user_id = auth.uid())
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = active_calls.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "prod_call_transcripts_select_member" on public.call_transcripts;
create policy "prod_call_transcripts_select_member"
on public.call_transcripts for select to authenticated
using (
  (workspace_id is null and user_id = auth.uid())
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = call_transcripts.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "prod_agents_select_member" on public.agents;
create policy "prod_agents_select_member"
on public.agents for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = agents.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "prod_agents_write_admin" on public.agents;
create policy "prod_agents_write_admin"
on public.agents for all to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = agents.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
)
with check (
  user_id = auth.uid()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = agents.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);

drop policy if exists "prod_usage_select_member" on public.usage_events;
create policy "prod_usage_select_member"
on public.usage_events for select to authenticated
using (
  (workspace_id is null and user_id = auth.uid())
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = usage_events.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "prod_campaigns_select_member" on public.campaigns;
create policy "prod_campaigns_select_member"
on public.campaigns for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = campaigns.workspace_id and wm.user_id = auth.uid()
  )
);

drop policy if exists "prod_campaigns_write_admin" on public.campaigns;
create policy "prod_campaigns_write_admin"
on public.campaigns for all to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = campaigns.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
)
with check (
  user_id = auth.uid()
  or exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = campaigns.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);

drop policy if exists "prod_billing_select_admin" on public.billing_accounts;
create policy "prod_billing_select_admin"
on public.billing_accounts for select to authenticated
using (
  exists (
    select 1 from public.workspace_members wm
    where wm.workspace_id = billing_accounts.workspace_id
      and wm.user_id = auth.uid()
      and wm.role in ('owner', 'admin')
  )
);
